import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — Zerrow" },
      { name: "description", content: "The terms that govern your use of Zerrow." },
      { property: "og:title", content: "Terms & Conditions — Zerrow" },
      { property: "og:description", content: "The terms that govern your use of Zerrow." },
    ],
  }),
  component: TermsPage,
});

const PAPER = "#f5f3ee";
const PAPER_DEEP = "#e8e4dd";
const INK = "#0d0d0d";
const INK_SOFT = "#2d2d2d";
const sora = { fontFamily: "'Sora', ui-sans-serif, system-ui, sans-serif" };
const manrope = { fontFamily: "'Manrope', ui-sans-serif, system-ui, sans-serif" };

function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: PAPER, color: INK, ...manrope }}>
      <header className="sticky top-0 z-30 border-b backdrop-blur" style={{ borderColor: PAPER_DEEP, background: `${PAPER}cc` }}>
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link to="/" className="text-2xl font-bold tracking-tight" style={sora}>
            Zerrow<span style={{ color: INK_SOFT }}>.</span>
          </Link>
          <Link to="/login" className="rounded-full px-5 py-2 text-sm font-medium" style={{ background: INK, color: PAPER, ...sora }}>
            Sign in
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-24">
        <p className="mb-5 text-xs uppercase tracking-[0.25em]" style={{ color: INK_SOFT, ...sora }}>Legal</p>
        <h1 className="text-4xl font-bold tracking-tight md:text-6xl" style={sora}>Terms &amp; Conditions</h1>
        <p className="mt-4 text-sm" style={{ color: INK_SOFT }}>Last updated: May 20, 2026</p>

        <div className="mt-12 space-y-10 text-base leading-relaxed" style={{ color: INK_SOFT }}>
          <Section title="Acceptance">
            By creating an account or connecting Gmail, you agree to these terms. If you do not agree, do not use Zerrow.
          </Section>
          <Section title="The service">
            Zerrow is an AI-assisted email organizer for Gmail. It reads incoming messages and files them into folders you define. Features may change as the product evolves.
          </Section>
          <Section title="Your account">
            You are responsible for the activity on your account and for keeping your Google credentials secure. You must be at least 16 years old to use Zerrow.
          </Section>
          <Section title="Acceptable use">
            Don't use Zerrow to break the law, abuse Gmail's API quotas, reverse engineer the service, or attempt to access other users' data.
          </Section>
          <Section title="AI output">
            Classifications, summaries, and suggested replies are generated by AI and may be wrong. Review important messages yourself before acting on them. You are responsible for any email you send.
          </Section>
          <Section title="Termination">
            You can stop using Zerrow at any time by disconnecting Gmail and deleting your account from Settings. We may suspend or terminate accounts that violate these terms.
          </Section>
          <Section title="Liability">
            Zerrow is provided "as is" without warranty. To the maximum extent permitted by law, we are not liable for indirect or consequential damages arising from use of the service.
          </Section>
          <Section title="Changes">
            We may update these terms from time to time. Material changes will be announced in-app. Continued use after a change means you accept the new terms.
          </Section>
          <Section title="Contact">
            Questions? Email support@zerrow.app.
          </Section>
        </div>

        <div className="mt-16">
          <Link to="/" className="text-sm underline" style={sora}>← Back to home</Link>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-3 text-xl font-semibold" style={{ color: INK, ...sora }}>{title}</h2>
      <p>{children}</p>
    </section>
  );
}
