/**
 * Pure resolution logic for inbound CATEGORIES lines on CardDAV contact PUTs.
 *
 * iPhones that synced before the "stop emitting CATEGORIES" fix still hold
 * stale category tags (old leaf names, merged-away variants, flattened
 * "Parent / Child" paths) and echo them back on every contact edit. Matching
 * those echoes to existing groups — instead of blindly re-creating groups by
 * exact name — is what stops merged duplicates from resurrecting forever.
 */
import { normalizeCompanyName } from "@/lib/companies/normalize";

export type CategoryGroupInfo = {
  id: string;
  name: string;
  parentGroupId: string | null;
  autoGeneratedFromGroupId: string | null;
  autoCompanySubgroups: boolean;
};

export type CategoryResolution = {
  /** Existing groups that satisfy an inbound category. */
  matchedGroupIds: string[];
  /** Auto-company parents the contact should join as a manual member
   *  instead of a child group being created under them — the reconciler
   *  owns which brand subgroup the contact lands in. */
  joinParentIds: string[];
  /** Genuinely new groups to create. */
  toCreate: Array<{ name: string; parentGroupId: string | null }>;
};

const PATH_SEPARATORS = [" / ", " - "] as const;

function buildPathVariants(
  group: CategoryGroupInfo,
  byId: Map<string, CategoryGroupInfo>,
): string[] {
  const parts: string[] = [];
  let cursor: CategoryGroupInfo | undefined = group;
  let hops = 0;
  while (cursor && hops < 8) {
    parts.unshift(cursor.name);
    cursor = cursor.parentGroupId ? byId.get(cursor.parentGroupId) : undefined;
    hops++;
  }
  if (parts.length < 2) return [];
  return PATH_SEPARATORS.map((sep) => parts.join(sep).toLowerCase());
}

/** Pick one group from multiple candidates: prefer a group the contact is
 *  already in, then an auto-generated subgroup, otherwise report ambiguity
 *  (null) so the caller skips rather than guesses. */
function pickPreferred(
  candidates: CategoryGroupInfo[],
  memberGroupIds: Set<string>,
): CategoryGroupInfo | null {
  if (candidates.length === 0) return null;
  if (candidates.length === 1) return candidates[0];
  const member = candidates.filter((g) => memberGroupIds.has(g.id));
  if (member.length >= 1) return member[0];
  const auto = candidates.filter((g) => g.autoGeneratedFromGroupId);
  if (auto.length === 1) return auto[0];
  return null;
}

export function resolveCategoryTargets(
  categoryNames: string[],
  groups: CategoryGroupInfo[],
  opts: {
    /** Groups the contact currently belongs to (any auto_added state). */
    memberGroupIds: Set<string>;
    /** company_name_aliases: mild name_key → canonical company name. */
    nameAliases?: Map<string, string>;
  },
): CategoryResolution {
  const names = Array.from(
    new Set(categoryNames.map((n) => n.trim()).filter((n) => n.length > 0)),
  );

  const byId = new Map(groups.map((g) => [g.id, g]));
  const byLeaf = new Map<string, CategoryGroupInfo[]>();
  const byPath = new Map<string, CategoryGroupInfo[]>();
  const byNorm = new Map<string, CategoryGroupInfo[]>();
  for (const g of groups) {
    const leaf = g.name.toLowerCase();
    byLeaf.set(leaf, [...(byLeaf.get(leaf) ?? []), g]);
    for (const p of buildPathVariants(g, byId)) {
      byPath.set(p, [...(byPath.get(p) ?? []), g]);
    }
    const norm = normalizeCompanyName(g.name);
    if (norm) byNorm.set(norm, [...(byNorm.get(norm) ?? []), g]);
  }

  const matchedGroupIds = new Set<string>();
  const joinParentIds = new Set<string>();
  const toCreate: Array<{ name: string; parentGroupId: string | null }> = [];
  const pendingCreates = new Set<string>(); // "parentId|lower-name" dedupe

  const matchExisting = (name: string): CategoryGroupInfo | null | "skip" => {
    const lower = name.toLowerCase();
    // 1. Exact leaf name (case-insensitive).
    const leafHit = pickPreferred(byLeaf.get(lower) ?? [], opts.memberGroupIds);
    if (leafHit) return leafHit;
    if ((byLeaf.get(lower) ?? []).length > 1) return "skip";
    // 2. Flattened nested path ("Factory / Nissan", "Factory - Nissan").
    const pathHit = pickPreferred(byPath.get(lower) ?? [], opts.memberGroupIds);
    if (pathHit) return pathHit;
    if ((byPath.get(lower) ?? []).length > 1) return "skip";
    // 3. Mild-normalized name ("Nissan Inc" ≈ "Nissan").
    const norm = normalizeCompanyName(name);
    if (norm) {
      const cands = byNorm.get(norm) ?? [];
      const normHit = pickPreferred(cands, opts.memberGroupIds);
      if (normHit) return normHit;
      if (cands.length > 1) return "skip";
      // 4. Merged-away company name → canonical company → its group.
      const canonical = opts.nameAliases?.get(norm);
      if (canonical) {
        const canonNorm = normalizeCompanyName(canonical);
        const canonCands = [
          ...(byLeaf.get(canonical.toLowerCase()) ?? []),
          ...(canonNorm ? (byNorm.get(canonNorm) ?? []) : []),
        ];
        const dedup = [...new Map(canonCands.map((g) => [g.id, g])).values()];
        const aliasHit = pickPreferred(dedup, opts.memberGroupIds);
        if (aliasHit) return aliasHit;
        // Known merged-away name with no surviving group: the reconciler
        // owns it — never re-create.
        return "skip";
      }
    }
    return null;
  };

  for (const name of names) {
    const hit = matchExisting(name);
    if (hit === "skip") continue;
    if (hit) {
      matchedGroupIds.add(hit.id);
      continue;
    }

    // 5. Nothing matched — create, honoring path-shaped names.
    let created = false;
    for (const sep of PATH_SEPARATORS) {
      if (!name.includes(sep)) continue;
      const segments = name.split(sep).map((s) => s.trim()).filter(Boolean);
      if (segments.length < 2) continue;
      // Resolve the prefix chain strictly from the root.
      let parent: CategoryGroupInfo | null = null;
      let resolved = true;
      for (const seg of segments.slice(0, -1)) {
        const segLower = seg.toLowerCase();
        const next = groups.find(
          (g) =>
            g.name.toLowerCase() === segLower &&
            (g.parentGroupId ?? null) === (parent?.id ?? null),
        );
        if (!next) {
          resolved = false;
          break;
        }
        parent = next;
      }
      if (!resolved || !parent) continue;
      const leafName = segments[segments.length - 1];
      if (parent.autoCompanySubgroups) {
        // The reconciler mints brand subgroups under this parent; adding a
        // manual child would just duplicate its work.
        joinParentIds.add(parent.id);
      } else {
        const leafHit = matchExisting(leafName);
        if (leafHit && leafHit !== "skip" && leafHit.parentGroupId === parent.id) {
          matchedGroupIds.add(leafHit.id);
        } else if (leafHit === "skip") {
          // ambiguous — leave alone
        } else {
          const dedupKey = `${parent.id}|${leafName.toLowerCase()}`;
          if (!pendingCreates.has(dedupKey)) {
            pendingCreates.add(dedupKey);
            toCreate.push({ name: leafName, parentGroupId: parent.id });
          }
        }
      }
      created = true;
      break;
    }
    if (!created) {
      const dedupKey = `|${name.toLowerCase()}`;
      if (!pendingCreates.has(dedupKey)) {
        pendingCreates.add(dedupKey);
        toCreate.push({ name, parentGroupId: null });
      }
    }
  }

  return {
    matchedGroupIds: [...matchedGroupIds],
    joinParentIds: [...joinParentIds],
    toCreate,
  };
}

/** Plan the membership diff for a contact after category resolution.
 *  Auto rows (`auto_added=true`) are server-managed and never touched;
 *  auto-generated subgroups never receive manual rows — the reconciler
 *  fully owns their membership. */
export function planCategoryMembership(opts: {
  resolvedGroupIds: string[];
  currentMemberships: Array<{ groupId: string; autoAdded: boolean }>;
  autoGeneratedGroupIds: Set<string>;
}): { toInsert: string[]; toDelete: string[] } {
  const desired = new Set(opts.resolvedGroupIds);
  const current = new Set(opts.currentMemberships.map((m) => m.groupId));
  const toInsert = [...desired].filter(
    (g) => !current.has(g) && !opts.autoGeneratedGroupIds.has(g),
  );
  const toDelete = opts.currentMemberships
    .filter(
      (m) =>
        !m.autoAdded &&
        !desired.has(m.groupId) &&
        !opts.autoGeneratedGroupIds.has(m.groupId),
    )
    .map((m) => m.groupId);
  return { toInsert, toDelete };
}
