import { describe, expect, it } from "vitest";
import {
  planCategoryMembership,
  resolveCategoryTargets,
  type CategoryGroupInfo,
} from "./categories.server";

function group(
  id: string,
  name: string,
  overrides: Partial<CategoryGroupInfo> = {},
): CategoryGroupInfo {
  return {
    id,
    name,
    parentGroupId: null,
    autoGeneratedFromGroupId: null,
    autoCompanySubgroups: false,
    ...overrides,
  };
}

// Mirrors the production shape: "Factory" auto-generates brand subgroups,
// "Vendor" has an ordinary manual child, "Dealers" is flat.
const FACTORY = group("f", "Factory", { autoCompanySubgroups: true });
const NISSAN = group("n", "Nissan", {
  parentGroupId: "f",
  autoGeneratedFromGroupId: "f",
});
const DEALERS = group("d", "Dealers");
const VENDOR = group("v", "Vendor");
const SOFTWARE = group("s", "Software", { parentGroupId: "v" });
const GROUPS = [FACTORY, NISSAN, DEALERS, VENDOR, SOFTWARE];

const NO_MEMBERS = { memberGroupIds: new Set<string>() };

describe("resolveCategoryTargets", () => {
  it("matches exact leaf names case-insensitively", () => {
    const res = resolveCategoryTargets(["nissan", "DEALERS"], GROUPS, NO_MEMBERS);
    expect(res.matchedGroupIds.sort()).toEqual(["d", "n"]);
    expect(res.toCreate).toEqual([]);
  });

  it("matches flattened path echoes in both separator styles", () => {
    const slash = resolveCategoryTargets(["Factory / Nissan"], GROUPS, NO_MEMBERS);
    expect(slash.matchedGroupIds).toEqual(["n"]);
    expect(slash.toCreate).toEqual([]);

    const dash = resolveCategoryTargets(["Factory - Nissan"], GROUPS, NO_MEMBERS);
    expect(dash.matchedGroupIds).toEqual(["n"]);
    expect(dash.toCreate).toEqual([]);
  });

  it("matches by mild-normalized name", () => {
    const res = resolveCategoryTargets(["Nissan Inc."], GROUPS, NO_MEMBERS);
    expect(res.matchedGroupIds).toEqual(["n"]);
    expect(res.toCreate).toEqual([]);
  });

  it("resolves merged-away company names through aliases", () => {
    const res = resolveCategoryTargets(["Nissan Motor Acceptance Company"], GROUPS, {
      ...NO_MEMBERS,
      nameAliases: new Map([["nissan motor acceptance company", "Nissan"]]),
    });
    expect(res.matchedGroupIds).toEqual(["n"]);
    expect(res.toCreate).toEqual([]);
  });

  it("never re-creates an aliased name whose group is gone", () => {
    const res = resolveCategoryTargets(["Kia America Inc"], GROUPS, {
      ...NO_MEMBERS,
      nameAliases: new Map([["kia america", "Kia"]]),
    });
    expect(res.matchedGroupIds).toEqual([]);
    expect(res.toCreate).toEqual([]);
    expect(res.joinParentIds).toEqual([]);
  });

  it("creates a path-shaped name under its resolved parent", () => {
    const res = resolveCategoryTargets(["Vendor / Hardware"], GROUPS, NO_MEMBERS);
    expect(res.matchedGroupIds).toEqual([]);
    expect(res.toCreate).toEqual([{ name: "Hardware", parentGroupId: "v" }]);
  });

  it("joins an auto-company parent instead of creating a child", () => {
    const res = resolveCategoryTargets(["Factory / Hyundai"], GROUPS, NO_MEMBERS);
    expect(res.matchedGroupIds).toEqual([]);
    expect(res.toCreate).toEqual([]);
    expect(res.joinParentIds).toEqual(["f"]);
  });

  it("creates unknown flat names at top level", () => {
    const res = resolveCategoryTargets(["Golf Buddies"], GROUPS, NO_MEMBERS);
    expect(res.toCreate).toEqual([{ name: "Golf Buddies", parentGroupId: null }]);
  });

  it("prefers a group the contact is already in on normalized multi-match", () => {
    const nissanInc = group("n2", "Nissan Inc", { parentGroupId: "d" });
    const res = resolveCategoryTargets(["Nissan Corp."], [...GROUPS, nissanInc], {
      memberGroupIds: new Set(["n2"]),
    });
    expect(res.matchedGroupIds).toEqual(["n2"]);
    expect(res.toCreate).toEqual([]);
  });

  it("skips (no match, no create) on unresolvable ambiguity", () => {
    const nissanInc = group("n2", "Nissan Inc", { parentGroupId: "d" });
    const nissanCo = group("n3", "Nissan Co", { parentGroupId: "v" });
    const res = resolveCategoryTargets(
      ["Nissan Corp."],
      [DEALERS, VENDOR, nissanInc, nissanCo],
      NO_MEMBERS,
    );
    expect(res.matchedGroupIds).toEqual([]);
    expect(res.toCreate).toEqual([]);
  });

  it("dedupes repeated and blank category names", () => {
    const res = resolveCategoryTargets(
      ["Nissan", " Nissan ", "", "Golf Buddies", "golf buddies"],
      GROUPS,
      NO_MEMBERS,
    );
    expect(res.matchedGroupIds).toEqual(["n"]);
    expect(res.toCreate).toEqual([{ name: "Golf Buddies", parentGroupId: null }]);
  });
});

describe("planCategoryMembership", () => {
  it("never touches auto rows and never writes into auto-generated groups", () => {
    const plan = planCategoryMembership({
      resolvedGroupIds: ["n", "d"],
      currentMemberships: [
        { groupId: "f", autoAdded: true }, // auto row, unlisted → kept
        { groupId: "n", autoAdded: false }, // manual row in auto-generated group → kept
      ],
      autoGeneratedGroupIds: new Set(["n"]),
    });
    // "n" is auto-generated → no manual insert even though resolved.
    expect(plan.toInsert).toEqual(["d"]);
    expect(plan.toDelete).toEqual([]);
  });

  it("diffs only manual rows against the resolved set", () => {
    const plan = planCategoryMembership({
      resolvedGroupIds: ["d"],
      currentMemberships: [
        { groupId: "d", autoAdded: false }, // listed → kept
        { groupId: "v", autoAdded: false }, // manual, unlisted → removed
        { groupId: "f", autoAdded: true }, // auto, unlisted → kept
      ],
      autoGeneratedGroupIds: new Set(["n"]),
    });
    expect(plan.toInsert).toEqual([]);
    expect(plan.toDelete).toEqual(["v"]);
  });

  it("inserts new manual memberships for resolved groups", () => {
    const plan = planCategoryMembership({
      resolvedGroupIds: ["d", "v", "f"],
      currentMemberships: [{ groupId: "d", autoAdded: false }],
      autoGeneratedGroupIds: new Set(["n"]),
    });
    expect(plan.toInsert.sort()).toEqual(["f", "v"]);
    expect(plan.toDelete).toEqual([]);
  });
});
