/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFoldersRouteImport } from './routes/_authenticated/folders'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google-oauth-callback'
import { Route as ApiPublicGmailWebhookRouteImport } from './routes/api/public/gmail-webhook'
import { Route as ApiPublicGmailPollRouteImport } from './routes/api/public/gmail-poll'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFoldersRoute = AuthenticatedFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google-oauth-callback',
    path: '/api/public/google-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGmailWebhookRoute = ApiPublicGmailWebhookRouteImport.update({
  id: '/api/public/gmail-webhook',
  path: '/api/public/gmail-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmailPollRoute = ApiPublicGmailPollRouteImport.update({
  id: '/api/public/gmail-poll',
  path: '/api/public/gmail-poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/gmail-poll': typeof ApiPublicGmailPollRoute
  '/api/public/gmail-webhook': typeof ApiPublicGmailWebhookRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/gmail-poll': typeof ApiPublicGmailPollRoute
  '/api/public/gmail-webhook': typeof ApiPublicGmailWebhookRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/folders': typeof AuthenticatedFoldersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/gmail-poll': typeof ApiPublicGmailPollRoute
  '/api/public/gmail-webhook': typeof ApiPublicGmailWebhookRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/folders'
    | '/settings'
    | '/api/public/gmail-poll'
    | '/api/public/gmail-webhook'
    | '/api/public/google-oauth-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/folders'
    | '/settings'
    | '/'
    | '/api/public/gmail-poll'
    | '/api/public/gmail-webhook'
    | '/api/public/google-oauth-callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/folders'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/api/public/gmail-poll'
    | '/api/public/gmail-webhook'
    | '/api/public/google-oauth-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicGmailPollRoute: typeof ApiPublicGmailPollRoute
  ApiPublicGmailWebhookRoute: typeof ApiPublicGmailWebhookRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/folders': {
      id: '/_authenticated/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthenticatedFoldersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/google-oauth-callback': {
      id: '/api/public/google-oauth-callback'
      path: '/api/public/google-oauth-callback'
      fullPath: '/api/public/google-oauth-callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail-webhook': {
      id: '/api/public/gmail-webhook'
      path: '/api/public/gmail-webhook'
      fullPath: '/api/public/gmail-webhook'
      preLoaderRoute: typeof ApiPublicGmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail-poll': {
      id: '/api/public/gmail-poll'
      path: '/api/public/gmail-poll'
      fullPath: '/api/public/gmail-poll'
      preLoaderRoute: typeof ApiPublicGmailPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFoldersRoute: typeof AuthenticatedFoldersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFoldersRoute: AuthenticatedFoldersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicGmailPollRoute: ApiPublicGmailPollRoute,
  ApiPublicGmailWebhookRoute: ApiPublicGmailWebhookRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
