ALTER PUBLICATION supabase_realtime DROP TABLE public.emails;

ALTER PUBLICATION supabase_realtime ADD TABLE public.emails (
  id,
  user_id,
  gmail_account_id,
  gmail_message_id,
  thread_id,
  from_addr,
  from_name,
  to_addrs,
  cc,
  list_id,
  in_reply_to,
  subject,
  snippet,
  received_at,
  is_read,
  is_archived,
  has_attachment,
  folder_id,
  classified_by,
  classification_reason,
  ai_summary,
  ai_confidence,
  matched_filter_ids,
  matched_folder_ids,
  raw_labels,
  snoozed_until,
  forwarded_to,
  forwarded_at,
  processed_at,
  published_at_ms,
  created_at
);